# Generated by Django 6.0.4 on 2026-04-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0002_alter_offer_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
    ]
