services:
  - type: web
    name: coderr-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: coderr-v4g3.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://coderr-frontend.onrender.com
